--Dependencias SYSTEM
 
SELECT OBJECT_TYPE, COUNT(*)
FROM DBA_OBJECTS 
WHERE STATUS = 'INVALID'
GROUP BY OBJECT_TYPE;

SELECT * 
FROM DBA_DEPENDENCIES 
WHERE REFERENCED_NAME = 'LOCALIDADES';

SET SERVEROUTPUT ON

EXECUTE DBMS_UTILITY.GET_DEPENDENCY('TABLE','HR','LOCALIDADES');