--Dependencias

SELECT * 
FROM USER_DEPENDENCIES
WHERE REFERENCED_NAME = 'STANDARD' 
AND REFERENCED_OWNER = 'SYS';

-- Validez de objetos

SELECT * 
FROM USER_OBJECTS
WHERE OBJECT_NAME = 'NUM_JAPON';

-- Creacion de dependencias

CREATE TABLE LOCALIDADES AS
SELECT * FROM LOCATIONS;

SELECT *
FROM LOCALIDADES;

CREATE VIEW JAPON AS
SELECT * FROM LOCALIDADES 
WHERE COUNTRY_ID = 'JP';

SELECT * 
FROM JAPON;

ALTER TABLE LOCALIDADES MODIFY CITY VARCHAR2(200);

-- Compilacion manual

ALTER FUNCTION NUM_JAPON COMPILE;

-- Dependencia indirecta

CREATE OR REPLACE FUNCTION NUM_JAPON
RETURN NUMBER
IS
  x_ NUMBER;
BEGIN
  SELECT COUNT(*) INTO x_
  FROM JAPON;
  RETURN x_;
END NUM_JAPON;

SET SERVEROUTPUT ON

EXECUTE DBMS_UTILITY.GET_DEPENDENCY('TABLE','HR','LOCALIDADES');